import { Geist, Geist_Mono, SUSE } from "next/font/google";
import QueryProvider from "../../providers/QueryProvider";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/Footer";
import { Suspense } from "react";
import Loader from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Care Nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <header>
        <Navbar />
      </header>

      <main className="bg-slate-50">
        <QueryProvider>
          <Suspense fallback={<Loader />}>
            {children}
          </Suspense>
        </QueryProvider>
      </main>

      <Footer />
      {/* <Suspense fallback={null}> */}
      {/* <AuthHandler /> */}
      {/* </Suspense> */}
      {/* <Suspense fallback={null}> */}
      {/* <AuthAlert /> */}
      {/* </Suspense> */}
    </div >
  );
}
